{
 "title": "Experiment",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "example data created per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(exampleData_created_total[1m])*60"
    }
   ]
  },
  {
   "title": "sum(count_over_time({job=\"monitoring-demo\"}[30m])) by (level)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring-demo\"}[30m])) by (level)"
    }
   ]
  },
  {
   "title": "avg request duration in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum/http_server_requests_seconds_count*1000"
    }
   ]
  },
  {
   "title": "{job=\"monitoring-demo\",level=\"INFO\"}",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"monitoring-demo\",level=\"INFO\"}"
    }
   ]
  }
 ]
}