server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://185217:eyJrIjoiZmEyMzk0MjUyMWYxMTllODRhOTgyNjFlMWMwZDFlMGJjMGIzZmQwMyIsIm4iOiJSaW5hdGlrIiwiaWQiOjYyMDk1Nn0=@logs-prod-eu-west-0.grafana.net/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost7
        labels:
          job: monitoring-demo
          __path__: /var/log/monitoring.log
    pipeline_stages:
      - json:
          expressions:
            level: level
      - labels:
          level:
